# Generated by Django 5.2.9 on 2026-01-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='loginBackgroundImg/default.jpg', null=True, upload_to='loginBackgroundImg/%Y/%m/%d/', verbose_name='登录背景图')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '登录界面背景图',
                'verbose_name_plural': '登录界面背景图',
            },
        ),
    ]
