# Generated by Django 5.2.9 on 2026-01-07 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsetting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginimage',
            old_name='avatar',
            new_name='image',
        ),
    ]
