# Generated by Django 5.2.9 on 2026-01-06 09:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guser',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.jpg', null=True, upload_to='avatars/%Y/%m/%d/', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='guser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='guser',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女'), ('O', '其他'), ('U', '未知')], default='U', max_length=1, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='guser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间'),
        ),
        migrations.AddField(
            model_name='guser',
            name='signature',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='个性签名'),
        ),
    ]
