# Generated by Django 5.2.9 on 2026-01-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_guser_avatar_guser_created_at_guser_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guser',
            name='last_login',
        ),
        migrations.AddField(
            model_name='guser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='guser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
