# Generated by Django 5.2.9 on 2026-01-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_alter_photo_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_photo',
            field=models.ImageField(default='cover_photo/default.jpg', upload_to='cover_photo/%Y/%m/', verbose_name='相册封面'),
        ),
    ]
